name: Java CI Build

on:
  workflow_dispatch:
  push:
    branches: [ ci-build-dependency ]
  pull_request:
    branches: [ ci-build-dependency ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B clean compile

      - name: Run unit tests
        run: mvn test

      - name: Package application
        run: mvn package
